### ISSUE TITLE
Faire fonctionner l'intégration continue

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-A2019#1]
le build ne fonctionne pas pour le moment.
Le débugger et le faire tourner.

poster ici votre nom prénom et le lien vers le CI ( exemple : https://travis-ci.org/LPA2-Automne2016/projet-back-A2019/builds/587410162 )

**Comment by LPA2-Automne2016** [comment]
ATTENTION SUIVEZ bien le tuto  : https://docs.travis-ci.com/user/tutorial/
cf paragraphe 5 : il faut un fichier .travis.yml pour que travis tourne !!!!

**Comment by deove** [comment]
https://travis-ci.org/deove/projet-lp4a-A2019
YAN ZEYU

**Comment by AurelienVasseur** [comment]
https://travis-ci.org/AurelienVasseur/Projet-LP4B-backend/builds/587483102
Aurélien VASSEUR

**Comment by hicham-arahhou** [comment]
https://travis-ci.org/hicham-arahhou/LP4A-backend-A2019/builds/587621763
Hicham ARAHHOU

**Comment by ljl19971006** [comment]
https://travis-ci.org/ljl19971006/backend/builds/587802532
JIALE LI

**Comment by FeiyiZHAO** [comment]
https://travis-ci.org/FeiyiZHAO/PROJET-BACK-A/builds/587806421
Feiyi ZHAO

**Comment by haolingzhang1** [comment]
https://travis-ci.org/haolingzhang1/projet1-test3/builds/587812316
HaolingZHANG

**Comment by deove** [comment]
https://travis-ci.org/deove/projet-lp4a-A2019/builds/587808595
YAN ZEYU (j'ai soucis que le lien est different avec les autres, alors j'ai envoye encore une fois)

**Comment by 125241576** [comment]
Honghao XU
https://travis-ci.org/125241576/LP4A

**Comment by TheoCollignon** [comment]
Théo COLLIGNON
https://travis-ci.org/TheoCollignon/Backend/builds/588050179

**Comment by Qiao6651** [comment]
https://travis-ci.org/Qiao6651/Projet-lp4a/builds/588408633
Qiao HE

**Comment by wakkoyankee** [comment]
Hadrien ROTHEA
https://travis-ci.org/wakkoyankee/backend/builds/588605234

**Comment by EnzoP26** [comment]
Enzo PALERMO
https://travis-ci.org/EnzoP26/backend/builds/588851783

**Comment by Oumaimakhalil** [comment]
https://travis-ci.org/Oumaimakhalil/Backend/builds/588917304

**Comment by KevinFritsch** [comment]
Kevin FRITSCH
https://travis-ci.org/KevinFritsch/backend/builds/589030739

**Comment by LukaLam** [comment]
Luka LAMBALOT
https://travis-ci.org/LukaLam/Backend_application/builds/589043856

**Comment by NathanBodet** [comment]
Nathan BODET 
https://travis-ci.org/NathanBodet/Backend/builds/589087075

**Comment by yaosonia** [comment]
YAO Sonia

https://travis-ci.org/yaosonia/first-commit/builds/589177867

**Comment by ArnaudBistel** [comment]
Arnaud BISTEL
https://travis-ci.org/ArnaudBistel/backend/builds/589341475

**Comment by niggadou95** [comment]
https://travis-ci.org/niggadou95/backend/builds/589446212
Pape Doudou DIEYE

**Comment by YosefBayoude** [comment]
Yosef BAYOUDE IZOUKA
https://travis-ci.org/YosefBayoude/backend/builds/589428110

**Comment by OualidBougzime** [comment]
OUALID BOUGZIME
https://travis-ci.org/OualidBougzime/back

**Comment by QuentinGchrd** [comment]
Quentin GUICHARD
https://travis-ci.org/QuentinGchrd/LP4A-backend/builds/589955955

**Comment by FlavienGtlt** [comment]
Flavien GENTILT
https://travis-ci.org/FlavienGtlt/projet-back-a19/builds/589958386

**Comment by Aicanama** [comment]
Melounou Inès
https://travis-ci.org/Aicanama/projet-back-A2019/builds/590043020

**Comment by Julia185** [comment]
Julia ROLLAND
https://travis-ci.org/Julia185/projet-back-A2019/builds/590050303

**Comment by BastG57** [comment]
Bastien GAUJOUR
https://travis-ci.org/BastG57/Projet-Backend-A2019/builds/590085517

**Comment by Fabiensamj** [comment]
Fabien SAM
https://travis-ci.org/Fabiensamj/projet-back-A19/builds/590124241

**Comment by valent1chateau** [comment]
valentin castellon
https://travis-ci.org/valent1chateau/backend_FW19_LPA2/builds/590099364

**Comment by meldBayi** [comment]
https://travis-ci.com/meldBayi/projet_backend.svg?branch=master
Bayi DORE

**Comment by OualidBougzime** [comment]
https://travis-ci.org/OualidBougzime/back/builds/589852649
OUALID BOUGZIME

**Comment by meldBayi** [comment]
https://travis-ci.com/meldBayi/projet_backend/builds/129359007

DORE Bayi

**Comment by 125241576** [comment]
https://travis-ci.org/125241576/LP4A/builds/588416483
XU Honghao

**Comment by Bantou96** [comment]
https://travis-ci.org/Bantou96/backend/builds/590436840
FALL Cheikh Ahmed Tidiane

**Comment by LPA2-Automne2016** [comment]
:+1:
