### ISSUE TITLE
mise en place déploiement continu

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-A2019#6]
mettre en place l'intégration entre travis et heroku:
https://docs.travis-ci.com/user/deployment/heroku/

poster ici: le lien vers votre build travis 
le lien vers votre appli sous heroku

ATTENTION à la gem sqllite et à PG

**Comment by hicham-arahhou** [comment]
Build Travis : https://travis-ci.org/hicham-arahhou/LP4A-backend-A2019/builds/592696477
Application Heroku : https://lp4a-backend-a2019.herokuapp.com/

**Comment by KevinFritsch** [comment]
Build Travis : https://travis-ci.org/KevinFritsch/backend/builds/593040347
Application Heroku : https://dashboard.heroku.com/apps/backend--heroku-kfritsch

**Comment by wakkoyankee** [comment]
Hadrien ROTHEA
Build Travis : https://travis-ci.org/wakkoyankee/backend/builds/593177105
Heroku : https://wakkoyankee-backend.herokuapp.com/

**Comment by AurelienVasseur** [comment]
Build Travis : https://travis-ci.org/AurelienVasseur/Projet-LP4B-backend/builds/591082157 
Application Heroku : https://projet-lp4b-backend.herokuapp.com/students

**Comment by ArnaudBistel** [comment]
Arnaud Bistel

Build Travis : https://travis-ci.org/ArnaudBistel/backend/builds/592764303
Heroku: https://arnaud-bistel-backend.herokuapp.com/

**Comment by Julia185** [comment]
Julia ROLLAND
Build Travis : https://travis-ci.org/Julia185/projet-back-A2019/builds/592457344
Application Heroku : https://projet-back-end.herokuapp.com/

**Comment by ljl19971006** [comment]
Jiale LI
Travis： https://travis-ci.org/ljl19971006/backend/builds/593222231
Heroku：https://lijiale.herokuapp.com/

**Comment by FeiyiZHAO** [comment]
Feiyi ZHAO
Travis : https://travis-ci.org/FeiyiZHAO/LPA4/builds/593273187
Heroku : https://lp4a-fzhao.herokuapp.com/

**Comment by niggadou95** [comment]
Pape Doudou DIEYE
https://travis-ci.org/niggadou95/backend/builds/593245261
https://lpa-backend-a19.herokuapp.com/students

**Comment by Oumaimakhalil** [comment]
Oumaima KHALIL
Travis: https://travis-ci.org/Oumaimakhalil/lpa2/builds/592974084
Heroku: https://lpa2backend.herokuapp.com/

**Comment by haolingzhang1** [comment]
Haoling ZHANG
Travis:    https://travis-ci.org/haolingzhang1/LP4A_backend/builds/593291123
Heroku: https://cryptic-shelf-52465.herokuapp.com/

**Comment by OualidBougzime** [comment]
OUALID BOUGZIME
Heroku : https://oualidlpa2back.herokuapp.com/students
Travis : https://travis-ci.org/OualidBougzime/back/builds/593254765

**Comment by Oumaimakhalil** [comment]
Oumaima KHALIL
Travis: https://travis-ci.org/Oumaimakhalil/lpa2/builds/592974084
Heroku: https://lpa2backend.herokuapp.com/students

**Comment by Qiao6651** [comment]
Qiao HE
Travis: https://www.travis-ci.org/Qiao6651/Projet-lp4a/builds/593331481
Heroku:https://projet-lp4a.herokuapp.com/

**Comment by YosefBayoude** [comment]
Travis: https://travis-ci.org/YosefBayoude/backend/builds/593313757
Heroku: https://yosefbackend.herokuapp.com/students

**Comment by LukaLam** [comment]
Luka LAMBALOT
Travis : https://travis-ci.org/LukaLam/Backend_application/builds/592517189
Heroku: https://backendaplication.herokuapp.com/students

**Comment by Aicanama** [comment]
MELOUNOU ines
Travis : https://travis-ci.org/Aicanama/projet-back-A2019/builds/593190456
Heroku : https://test-heroku-travis.herokuapp.com/

**Comment by valent1chateau** [comment]
valentin castellon
https://travis-ci.org/valent1chateau/backend_FW19_LPA2/builds/592479381
https://backend-fw19-lpa2.herokuapp.com/

**Comment by EdgarDupont** [comment]
Edgar Dupont
https://travis-ci.org/EdgarDupont/BackEnd
https://dashboard.heroku.com/apps/appedgardupont/deploy/github

**Comment by haolingzhang1** [comment]
haoling ZHANG
TRAVIS:
https://travis-ci.org/haolingzhang1/LP4A_backend/builds/593408664
HEROKU:
https://salty-plains-69715.herokuapp.com/
(c'est le bon lien ,il manque des choses dan le lien precedent)

**Comment by EnzoP26** [comment]
Enzo PALERMO
Travis : https://travis-ci.org/EnzoP26/backend/builds/593446759
Heroku : https://enzop26-backend.herokuapp.com/students

**Comment by QuentinGchrd** [comment]
Quentin GUICHARD

https://travis-ci.org/QuentinGchrd/LP4A-backend/builds/593446189

https://lp4a-backend.herokuapp.com/students

**Comment by Bantou96** [comment]
Cheikh Ahmed Tidiane FALL
build travis: https://travis-ci.org/Bantou96/backend/jobs/593446328
Heroku: https://lp4abantou.herokuapp.com/students

**Comment by deove** [comment]
YAN ZEYU
travis: https://travis-ci.org/deove/projet-lp4a-A2019/builds/593498401
heroku: https://projet-yzy.herokuapp.com/students
