### ISSUE TITLE
mettre en place le counter

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-A2019#8]
faire fonctionner la totalité du counter 

poster le lien vers le build
le lien vers le code des tests

**Comment by hicham-arahhou** [comment]
Build Travis : https://travis-ci.org/hicham-arahhou/LP4A-backend-A2019/builds/593469187
Test Counters - Model : https://github.com/hicham-arahhou/LP4A-backend-A2019/blob/master/test/models/counter_test.rb
Test Counters - Controller : https://github.com/hicham-arahhou/LP4A-backend-A2019/blob/master/test/controllers/counters_controller_test.rb

**Comment by KevinFritsch** [comment]
Build Travis : https://travis-ci.org/KevinFritsch/backend/builds/593470222
Test Counters - Model : https://github.com/KevinFritsch/backend/blob/master/test/models/counter_test.rb
Test Counters - Controller : https://github.com/KevinFritsch/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by ArnaudBistel** [comment]
Arnaud Bistel

Build Travis : hhttps://travis-ci.org/ArnaudBistel/backend/builds/593566310
Test Counters - Model : https://github.com/ArnaudBistel/backend/blob/branch_utbm/test/models/counter_test.rb
Test Counters - Controller : https://github.com/ArnaudBistel/backend/blob/branch_utbm/test/controllers/counters_controller_test.rb

**Comment by YosefBayoude** [comment]
Yosef Bayoude

Travis : https://travis-ci.org/YosefBayoude/backend/builds/593563304
Test Counters - Model : https://github.com/YosefBayoude/backend/blob/master/test/models/counter_test.rb
Test Counters - Controller : https://github.com/ArnaudBistel/backend/blob/branch_utbm/test/controllers/counters_controller_test.rb

**Comment by YosefBayoude** [comment]
Yosef Bayoude

Travis : https://travis-ci.org/YosefBayoude/backend/builds/593563304
Test Counters - Model : https://github.com/YosefBayoude/backend/blob/master/test/models/counter_test.rb
Test Counters - Controller : https://github.com/YosefBayoude/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by OualidBougzime** [comment]
OUALID BOUGZIME

Travis : https://travis-ci.org/OualidBougzime/back/builds/593572963
Test Counters - Model : https://github.com/OualidBougzime/back/blob/master/test/models/counter_test.rb
Test Counters - Controller : https://github.com/OualidBougzime/back/blob/master/test/controllers/counters_controller_test.rb

**Comment by haolingzhang1** [comment]
Haoling ZHANG
Travis:  https://travis-ci.org/haolingzhang1/LP4A_backend/builds/593613258
Test Counters - Model : 
https://github.com/haolingzhang1/LP4A_backend/blob/master/test/models/counter_test.rb
Test Counters - Controller : 
https://github.com/haolingzhang1/LP4A_backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by FeiyiZHAO** [comment]
Feiyi ZHAO
Travis : https://travis-ci.org/FeiyiZHAO/LPA4/builds/593689068
Test Counters - Model : https://github.com/FeiyiZHAO/LPA4/blob/master/test/models/counter_test.rb
Test Counters - Controller ：https://github.com/FeiyiZHAO/LPA4/blob/master/test/controllers/counters_controller_test.rb

**Comment by deove** [comment]
YAN ZEYU
Travis: https://travis-ci.org/deove/projet-lp4a-A2019/builds/594147147
Test Counters - Model:
https://github.com/deove/projet-lp4a-A2019/blob/master/test/models/counter_test.rb
Test Counters -Controller: 
https://github.com/deove/projet-lp4a-A2019/blob/master/test/controllers/counters_controller_test.rb

**Comment by 125241576** [comment]
XU Honghao
Travis:https://travis-ci.org/125241576/backend-LP4A/builds/594243858
Test Counters - Model:https://github.com/125241576/backend-LP4A/blob/master/test/models/counter_test.rb
Test Counters -Controller:https://github.com/125241576/backend-LP4A/blob/master/test/controllers/counters_controller_test.rb

**Comment by ljl19971006** [comment]
LI Jiale
Travis:https://travis-ci.org/ljl19971006/backend/builds/594291969
Test Counters-Model:https://github.com/ljl19971006/backend/blob/master/test/models/counter_test.rb
Test Counters-Controller:https://github.com/ljl19971006/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by Oumaimakhalil** [comment]
Oumaima KHALIL
Travis: 
https://travis-ci.org/Oumaimakhalil/lpa2/builds/595029641

Test Counters - Model:
https://github.com/Oumaimakhalil/lpa2/blob/master/test/models/counter_test.rb

Test Counters -Controller:
https://github.com/Oumaimakhalil/lpa2/blob/master/test/controllers/counters_controller_test.rb

**Comment by niggadou95** [comment]
Pape Doudou DIEYE
Travis : https://travis-ci.org/niggadou95/backend/builds/595222910

Test Counters - Model: https://github.com/niggadou95/backend/blob/master/test/models/counter_test.rb

Test Counters -Controller: https://github.com/niggadou95/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by AurelienVasseur** [comment]
Aurélien VASSEUR

Build Travis : 
https://travis-ci.org/AurelienVasseur/Projet-LP4B-backend/builds/593560166

Test Counters - Model : 
https://github.com/AurelienVasseur/Projet-LP4B-backend/blob/master/test/models/counter_test.rb

Test Counters - Controller : 
https://github.com/AurelienVasseur/Projet-LP4B-backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by Qiao6651** [comment]
HE Qiao

Build Travis:
https://travis-ci.org/Qiao6651/Projet-lp4a/builds/596317984

Test Counters - Model:
https://github.com/Qiao6651/Projet-lp4a/blob/master/test/models/counter_test.rb

Test Counters - Controller:
https://github.com/Qiao6651/Projet-lp4a/blob/master/test/controllers/counters_controller_test.rb

**Comment by Bantou96** [comment]
Cheikh Ahmed Tidiane FALL

Build travis: 
https://travis-ci.org/Bantou96/backend/builds/597283693

Test Counters - Models:
https://github.com/Bantou96/backend/blob/master/test/models/counter_test.rb

Test Counters - Controllers:
https://github.com/Bantou96/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by LukaLam** [comment]
Luka LAMBALOT

Build travis:
https://travis-ci.org/LukaLam/Backend_application/builds/593470061

Test Counters - Model:
https://github.com/LukaLam/Backend_application/blob/master/test/models/counter_test.rb

Test Counters - Controllers:
https://github.com/LukaLam/Backend_application/blob/master/test/controllers/counters_controller_test.rb

**Comment by TheoCollignon** [comment]
Théo COLLIGNON

Build travis : https://travis-ci.org/TheoCollignon/Backend/builds/593559732
Test Counters - Model : https://github.com/TheoCollignon/Backend/blob/master/test/models/counter_test.rb
Test Counters - Controllers : https://github.com/TheoCollignon/Backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by EnzoP26** [comment]
Enzo PALERMO

Build Travis : https://travis-ci.org/EnzoP26/backend/builds/598238484
Test Counters - Model : https://github.com/EnzoP26/backend/blob/master/test/models/counter_test.rb
Test Counters - Controllers : https://github.com/EnzoP26/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by Julia185** [comment]
Julia ROLLAND

Build Travis : https://travis-ci.org/Julia185/projet-back-A2019/builds/598244824
Test Counters - Model : https://github.com/Julia185/projet-back-A2019/blob/master/test/models/counter_test.rb
Test Counters - Controllers : https://github.com/Julia185/projet-back-A2019/blob/master/test/controllers/counters_controller_test.rb

**Comment by Aicanama** [comment]
MELOUNOU Inès

**Build Travis :** https://travis-ci.org/Aicanama/projet-back-A2019/builds/598255477 
_(build failed because of heroku...)_
**Test Counters - Model** : https://github.com/Aicanama/projet-back-A2019/blob/master/test/models/student_test.rb
**Test Counters - Controllers :** https://github.com/Aicanama/projet-back-A2019/blob/master/test/controllers/students_controller_test.rb

**Comment by valent1chateau** [comment]
valentin castellon
travis : https://travis-ci.org/valent1chateau/backend_FW19_LPA2/builds/593468677
model : https://github.com/valent1chateau/backend_FW19_LPA2/blob/master/test/models/counter_test.rb
controller : https://github.com/valent1chateau/backend_FW19_LPA2/blob/master/test/controllers/counters_controller_test.rb

**Comment by wakkoyankee** [comment]
Hadrien ROTHEA
travis : https://travis-ci.org/wakkoyankee/backend/builds/598539315
model : https://github.com/wakkoyankee/backend/blob/master/test/models/counter_test.rb
controller : https://github.com/wakkoyankee/backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by Fabiensamj** [comment]
Fabien SAM

Travis:  https://travis-ci.org/Fabiensamj/projet-back-A19/builds/597256629
model: https://github.com/Fabiensamj/projet-back-A19/blob/master/test/models/counter_test.rb
controller:  https://github.com/Fabiensamj/projet-back-A19/blob/master/test/controllers/counters_controller_test.rb

**Comment by EdgarDupont** [comment]
Travis:
https://travis-ci.org/EdgarDupont/BackEnd/builds/599047296
Model:
https://github.com/EdgarDupont/BackEnd/blob/master/test/models/counter_test.rb
Controller:
https://github.com/EdgarDupont/BackEnd/blob/master/test/controllers/counters_controller_test.rb

**Comment by QuentinGchrd** [comment]
Quentin GUICHARD
Travis:
https://travis-ci.org/QuentinGchrd/LP4A-backend/builds/599124037
Model:
https://github.com/QuentinGchrd/LP4A-backend/blob/master/test/models/counter_test.rb
Controller: 
https://github.com/QuentinGchrd/LP4A-backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by meldBayi** [comment]
Bayi DORE

Build Travis : https://travis-ci.com/meldBayi/projet_backend/builds/133563011

Test Counters - Model :https://github.com/meldBayi/projet_backend/blob/master/test/models/counter_test.rb

Test Counters - Controller :https://github.com/meldBayi/projet_backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by meldBayi** [comment]
Bayi DORE

Build Travis : https://travis-ci.com/meldBayi/projet_backend/builds/133563011

Test Counters - Model: https://github.com/meldBayi/projet_backend/blob/master/test/models/counter_test.rb

Test Counters - Controller:
https://github.com/meldBayi/projet_backend/blob/master/test/controllers/counters_controller_test.rb

**Comment by yaosonia** [comment]
Yao Sonia

Travis CI: https://travis-ci.org/yaosonia/first-commit/builds/602826793

Model: https://github.com/yaosonia/first-commit/blob/master/test/models/counter_test.rb

Test Counters - Controller : https://github.com/yaosonia/first-commit/blob/master/test/controllers/counters_controller_test.rb

**Comment by LPA2-Automne2016** [comment]
:clap: :clap:
